title: Conference Deadlines
description: Countdowns to top conferences I am interested in
author: Originally by Abhishek Das

domain: "https://gratus907.github.io"
baseurl: "/conference-calendar"


markdown: kramdown

include: ['_pages']
